# Uncomment the next line to define a global platform for your project
platform :ios, '13.0'

target 'iOS' do
  # Comment the next line if you don't want to use dynamic frameworks
  # use_frameworks!
  pod 'Mapbox-iOS-SDK', '~> 5.3'

  # Pods for iOS

  target 'iOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'iOSUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
